// Carries a WebAssembly module inside a JavaScript page.
//
// A BSP page is a text object (tools/app2bsp.mjs), so a .wasm file cannot be
// vendored as it is - the wall Font Awesome's webfonts hit as well, and the
// way out is the same: the bytes travel as base64 inside a text file. For a
// font that file is the stylesheet (a data URI); for a WebAssembly module it
// is the script written here, which registers the base64 under the module's
// file name on window.z2ui5_cci_wasm. The control that needs the module
// decodes it and hands the bytes to its library directly, so nothing is
// fetched at run time - which is also why no connect-src entry is needed for
// it.
//
// The base64 is written as an array of short string literals, one per line,
// rather than as one literal continued with backslashes (the way
// tools/wrap-lines.mjs splits an overlong string inside a library). Nothing
// here is upstream code whose bytes have to stay recognisable, so the format
// can be chosen for robustness instead: every line ends in `",`, which stays
// valid JavaScript whatever whitespace a system pads it with.

// The global the scripts register on. BarcodeScanner.js reads the same name.
export const GLOBAL = "z2ui5_cci_wasm";

// Characters of base64 per line - well inside the 240 tools/wrap-lines.mjs
// aims for, quotes and comma included.
const CHUNK = 200;

/**
 * The script that registers `bytes` as `window.z2ui5_cci_wasm[name]`.
 *
 * @param {Uint8Array} bytes the WebAssembly module
 * @param {string} name the key it is registered under, e.g. "zxing_reader.wasm"
 * @param {string} origin one line saying where the bytes come from
 * @returns {string}
 */
export function embedWasm(bytes, name, origin) {
  const base64 = Buffer.from(bytes).toString("base64");
  const lines = [];
  for (let i = 0; i < base64.length; i += CHUNK) {
    lines.push(`${JSON.stringify(base64.slice(i, i + CHUNK))},`);
  }
  return [
    `// ${origin}`,
    "// The WebAssembly module as base64, one chunk per line. Generated by",
    "// tools/vendor.mjs - see tools/embed-wasm.mjs for why it is shaped like this.",
    `(window.${GLOBAL} = window.${GLOBAL} || {})[${JSON.stringify(name)}] = [`,
    ...lines,
    '].join("");',
    "",
  ].join("\n");
}
